import Head from "next/head";

import Headline from "@/components/Headline";
import Portfolio from "@/components/portfolio/Portfolio";

const Home = () => {
  return (
    <>
      <Head>
        <title>Andre Thomas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headline />
      <Portfolio />
    </>
  );
};

export default Home;
